### ISSUE TITLE
[SM/Hyper Parameter Search] 필요성, 종류 공부 및 PPT 발표 - Martin이 관련 링크 및 학습자료 소개해주기

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/BinaryConnect#25]
@Ronalmoo 
블로그는 아래 링크를 보시고
1. [Bayesian Optimization 개요: 딥러닝 모델의 효과적인 hyperparameter 탐색 방법론 (1)](http://research.sualab.com/introduction/practice/2019/02/19/bayesian-optimization-overview-1.html)

유투브는 아래 것을 들으시면 됩니다.
1. [Tuning Process (C2W3L01)](https://www.youtube.com/watch?v=AXDByU3D1hA&list=PLkDaE6sCZn6Hn0vK8co82zjQtt3T2Nkqc&index=24)

2. [Hyperparameter Tuning in Practice (C2W3L03)](https://www.youtube.com/watch?v=wKkcBPp3F1Y&list=PLkDaE6sCZn6Hn0vK8co82zjQtt3T2Nkqc&index=26)

**Comment by Ronalmoo** [comment]
하이퍼파라미터의 중요성과 그것들을 직접 찾는 공수를 줄이기 위한 방법을 익히고  팀원들과 공유
