### ISSUE TITLE
[JH/Weight Histogram Visualization] MNIST `nn.module`에서 weights 추출하기; Colab - 5 days

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/BinaryConnect#29]
https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html
https://pytorch.org/docs/stable/_modules/torch/nn/modules/linear.html

**Comment by chromatices** [comment]
이슈가 발행된 이유 : MNIST 예제를 통해 가중치를 추출하여 향후 binary connect에서도 동일작업 수행
해야할 작업 : nn.module 참고하여 weight 추출
