### ISSUE TITLE
[JH/Paper] t-SNE 논문 리딩; Stochastic Neighbor Embedding

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/BinaryConnect#30]
https://www.youtube.com/watch?v=zpJwm7f7EXs
http://www.jmlr.org/papers/volume9/vandermaaten08a/vandermaaten08a.pdf

**Comment by chromatices** [comment]
이슈가 발행된 이유 : t-SNE 알고리즘을 이용한 딥러닝 모델의 시각화 구현
해야할 작업 : 논문 리딩 및 프레젠테이션 작성
