### ISSUE TITLE
[MH/BinaryConnect] BinaryLinear 모듈 GPU에서 작동하도록 수정

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/BinaryConnect#33]
`model.to("cuda:0")`로 모델이 GPU로 복사되면 에러가 납니다.
아마도 binarized weight가 model의 Parameter로 등록되지 않아서 binarized weight는 gpu로 복사가 안되서 발생하는 문제 같습니다.

해당 문제 한번 살펴보겠습니다.

**Comment by Ronalmoo** [comment]
네 알겠습니다.
